version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: overflowapi_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # redis: 
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

      

volumes:
  postgres-data:

networks:
  outside:
    name: host
    external: true